#!/usr/bin/env bash
set -euo pipefail

ENVIRONMENT="${1:-}"
if [[ -z "$ENVIRONMENT" ]]; then
  echo "Usage: $0 <local|dev|uat|prod>" >&2
  exit 1
fi

case "$ENVIRONMENT" in
  local|dev|uat|prod) ;;
  *) echo "Invalid environment: $ENVIRONMENT (use local, dev, uat, or prod)" >&2; exit 1 ;;
esac

# Convert environment to uppercase for prefix matching
ENV_PREFIX=$(echo "$ENVIRONMENT" | tr '[:lower:]' '[:upper:]')

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TFVARS_PATH="$PROJECT_ROOT/terraform/terraform.tfvars"

# Source .envrc to get all environment variables
# Set SKIP_DEFAULT_ENV to prevent .envrc from setting LOCAL defaults
if [[ -f "$PROJECT_ROOT/.envrc" ]]; then
  SKIP_DEFAULT_ENV=1 source "$PROJECT_ROOT/.envrc"
else
  echo "Error: .envrc file not found at $PROJECT_ROOT/.envrc" >&2
  exit 1
fi

# Helper function to escape terraform string values
escape_tf() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

# Helper function to write key-value pair to tfvars
write_kv() {
  local key="$1"
  local value="$2"
  if [[ -n "$value" ]]; then
    printf '%s = "%s"\n' "$key" "$(escape_tf "$value")" >> "$TFVARS_PATH"
  fi
}

# Helper function to write list values to tfvars
write_list() {
  local key="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    return
  fi
  local IFS=','
  local parts=($value)
  local out="["
  local first=1
  for part in "${parts[@]}"; do
    part="$(echo "$part" | xargs)"
    if [[ -z "$part" ]]; then
      continue
    fi
    if [[ $first -eq 0 ]]; then
      out+=", "
    fi
    out+="\"$(escape_tf "$part")\""
    first=0
  done
  out+="]"
  printf '%s = %s\n' "$key" "$out" >> "$TFVARS_PATH"
}

# Helper function to get environment-specific variable with fallback to common
get_var() {
  local var_name="$1"
  local env_var="${ENV_PREFIX}_${var_name}"
  
  # Try environment-specific variable first
  local value="${!env_var:-}"
  
  # If not found or empty, fallback to common variable
  if [[ -z "$value" ]]; then
    value="${!var_name:-}"
  fi
  
  echo "$value"
}

# Generate terraform.tfvars
rm -f "$TFVARS_PATH"
{
  echo "# Generated by scripts/generate_tfvars.sh for environment: $ENVIRONMENT"
  echo "# Generated at: $(date)"
} > "$TFVARS_PATH"

# ============================================================================
# Environment Configuration
# ============================================================================
{
  echo ""
  echo "# Environment Configuration"
} >> "$TFVARS_PATH"

write_kv "environment" "$(get_var 'ENVIRONMENT')"
write_kv "frontend_url" "$(get_var 'FRONTEND_URL')"
write_kv "api_domain" "$(get_var 'API_DOMAIN')"
write_kv "widget_cdn_domain" "$WIDGET_CDN_DOMAIN"

# ============================================================================
# Pinecone Vector Store (common)
# ============================================================================
{
  echo ""
  echo "# Pinecone Vector Store"
} >> "$TFVARS_PATH"

write_kv "pinecone_api_key" "$PINECONE_API_KEY"
write_kv "pinecone_host" "$PINECONE_HOST"
write_kv "pinecone_index" "$PINECONE_INDEX"

# ============================================================================
# Google OAuth (common)
# ============================================================================
{
  echo ""
  echo "# Google OAuth"
} >> "$TFVARS_PATH"

write_kv "google_client_id" "$GOOGLE_CLIENT_ID"
write_kv "google_client_secret" "$GOOGLE_CLIENT_SECRET"

# ============================================================================
# JWT (common)
# ============================================================================
{
  echo ""
  echo "# JWT Configuration"
} >> "$TFVARS_PATH"

write_kv "jwt_secret" "$JWT_SECRET"

# ============================================================================
# Cognito Hosted UI (common)
# ============================================================================
{
  echo ""
  echo "# Cognito Hosted UI"
} >> "$TFVARS_PATH"

write_kv "cognito_domain_prefix" "$COGNITO_DOMAIN_PREFIX"
write_kv "cognito_redirect_uri" "$(get_var 'COGNITO_REDIRECT_URI')"
write_list "cognito_callback_urls" "$COGNITO_CALLBACK_URLS"
write_list "cognito_logout_urls" "$COGNITO_LOGOUT_URLS"

# ============================================================================
# Stripe Configuration (environment-specific keys, common prices)
# ============================================================================
{
  echo ""
  echo "# Stripe Configuration (environment: $ENVIRONMENT)"
} >> "$TFVARS_PATH"

write_kv "stripe_secret_key" "$(get_var 'STRIPE_SECRET_KEY')"
write_kv "stripe_publishable_key" "$(get_var 'STRIPE_PUBLISHABLE_KEY')"
write_kv "stripe_webhook_secret" "$(get_var 'STRIPE_WEBHOOK_SECRET')"

# ============================================================================
# SES Configuration (common)
# ============================================================================
{
  echo ""
  echo "# SES Configuration"
} >> "$TFVARS_PATH"

write_kv "ses_domain" "$SES_DOMAIN"
write_kv "ses_from_email" "$SES_FROM_EMAIL"
write_kv "ses_reply_to_email" "$SES_REPLY_TO_EMAIL"
write_kv "ses_verification_email" "$SES_VERIFICATION_EMAIL"

echo ""
echo "✅ Generated terraform.tfvars for environment: $ENVIRONMENT"
echo "📍 Output: $TFVARS_PATH"
echo ""
echo "Summary:"
echo "  - Environment: $ENVIRONMENT"
echo "  - Frontend URL: $(get_var 'FRONTEND_URL')"
echo "  - API Domain: $(get_var 'API_DOMAIN')"
echo "  - Stripe Mode: $(if [[ $(get_var 'STRIPE_SECRET_KEY') == sk_live_* ]]; then echo 'LIVE ⚠️'; else echo 'TEST'; fi)"